version: '3.8'

services:
  app:
    build: .
    container_name: score_app
    ports:
      - "8777:8777"  
    volumes:
      - ./Scores.txt:/Scores.txt  #
    environment:
      - FLASK_RUN_HOST=0.0.0.0  
      - FLASK_RUN_PORT=8777  
    restart: unless-stopped  